//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class compra
    {
        public Nullable<int> cliid { get; set; }
        public int numemp { get; set; }
        public int idcarro { get; set; }
        public Nullable<System.DateTime> data { get; set; }
        public Nullable<decimal> preco { get; set; }
    
        public virtual carro carro { get; set; }
        public virtual cliente cliente { get; set; }
        public virtual empregado empregado { get; set; }
    }
}
