//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace fim.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class modelo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public modelo()
        {
            this.carros = new HashSet<carro>();
        }
    
        public int idmodelo { get; set; }
        public string modelo1 { get; set; }
        public Nullable<double> cilindrada { get; set; }
        public Nullable<int> potencia { get; set; }
        public Nullable<int> ano { get; set; }
        public Nullable<int> combustivel { get; set; }
        public Nullable<int> codmarca { get; set; }
        public string fotomodelo { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<carro> carros { get; set; }
        public virtual marca marca { get; set; }
    }
}
